# -*- coding: utf-8 -*-
"""Streamlit App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KB-PRVX-Fq6dnbxkW_C_Uxrd36v73gCH
"""

!pip install streamlit

import streamlit as st
import pickle

model = pickle.load(open("model.pkl", "rb"))

st.title("House Price Predictor")

price = st.number_input("Price")

if st.button("Predict"):
    prediction = model.predict([[price]])
    st.write(prediction)